### ISSUE TITLE
truffle init error

### ISSUE THREAD

**Issue by bhemeswararaoa** [trufflesuite/truffle-init#12]
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bar                                                                                                                e-box/master/truffle.js. Got error: getaddrinfo ENOTFOUND raw.githubusercontent.                                                                                                                com raw.githubusercontent.com:443. Please check the format of the requested reso                                                                                                                urce.
    at Request._callback (C:\Users\blockchain\AppData\Roaming\npm\node_modules\t                                                                                                                ruffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:45:1)
    at self.callback (C:\Users\blockchain\AppData\Roaming\npm\node_modules\truff                                                                                                                le\build\webpack:\~\request\request.js:185:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\blockchain\AppData\Roaming\npm\node_modu                                                                                                                les\truffle\build\webpack:\~\request\request.js:877:1)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

**Comment by bhemeswararaoa** [comment]
please give me the how to resolve it
